<?php
/**
 * ApproveOAuthAuthorizationRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Omnismith\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnismith API
 *
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.12
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Omnismith\Sdk\Model;

use \ArrayAccess;
use \Omnismith\Sdk\ObjectSerializer;

/**
 * ApproveOAuthAuthorizationRequest Class Doc Comment
 *
 * @category Class
 * @description Submits user consent approval for an authorized OAuth client and selected project workspace.
 * @package  Omnismith\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ApproveOAuthAuthorizationRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ApproveOAuthAuthorizationRequest';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'clientId' => 'string',
        'redirectUri' => 'string',
        'projectId' => 'string',
        'codeChallenge' => 'string',
        'codeChallengeMethod' => 'string',
        'scopes' => 'string[]',
        'state' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'clientId' => null,
        'redirectUri' => null,
        'projectId' => null,
        'codeChallenge' => null,
        'codeChallengeMethod' => null,
        'scopes' => null,
        'state' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'clientId' => false,
        'redirectUri' => false,
        'projectId' => false,
        'codeChallenge' => false,
        'codeChallengeMethod' => false,
        'scopes' => false,
        'state' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'clientId' => 'client_id',
        'redirectUri' => 'redirect_uri',
        'projectId' => 'project_id',
        'codeChallenge' => 'code_challenge',
        'codeChallengeMethod' => 'code_challenge_method',
        'scopes' => 'scopes',
        'state' => 'state'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'clientId' => 'setClientId',
        'redirectUri' => 'setRedirectUri',
        'projectId' => 'setProjectId',
        'codeChallenge' => 'setCodeChallenge',
        'codeChallengeMethod' => 'setCodeChallengeMethod',
        'scopes' => 'setScopes',
        'state' => 'setState'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'clientId' => 'getClientId',
        'redirectUri' => 'getRedirectUri',
        'projectId' => 'getProjectId',
        'codeChallenge' => 'getCodeChallenge',
        'codeChallengeMethod' => 'getCodeChallengeMethod',
        'scopes' => 'getScopes',
        'state' => 'getState'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CODE_CHALLENGE_METHOD_S256 = 'S256';
    public const CODE_CHALLENGE_METHOD_PLAIN = 'plain';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCodeChallengeMethodAllowableValues()
    {
        return [
            self::CODE_CHALLENGE_METHOD_S256,
            self::CODE_CHALLENGE_METHOD_PLAIN,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('clientId', $data ?? [], null);
        $this->setIfExists('redirectUri', $data ?? [], null);
        $this->setIfExists('projectId', $data ?? [], null);
        $this->setIfExists('codeChallenge', $data ?? [], null);
        $this->setIfExists('codeChallengeMethod', $data ?? [], null);
        $this->setIfExists('scopes', $data ?? [], null);
        $this->setIfExists('state', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['clientId'] === null) {
            $invalidProperties[] = "'clientId' can't be null";
        }
        if ($this->container['redirectUri'] === null) {
            $invalidProperties[] = "'redirectUri' can't be null";
        }
        if ($this->container['projectId'] === null) {
            $invalidProperties[] = "'projectId' can't be null";
        }
        if ($this->container['codeChallenge'] === null) {
            $invalidProperties[] = "'codeChallenge' can't be null";
        }
        $allowedValues = $this->getCodeChallengeMethodAllowableValues();
        if (!is_null($this->container['codeChallengeMethod']) && !in_array($this->container['codeChallengeMethod'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'codeChallengeMethod', must be one of '%s'",
                $this->container['codeChallengeMethod'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clientId
     *
     * @return string
     */
    public function getClientId()
    {
        return $this->container['clientId'];
    }

    /**
     * Sets clientId
     *
     * @param string $clientId Client identifier
     *
     * @return self
     */
    public function setClientId($clientId)
    {
        if (is_null($clientId)) {
            throw new \InvalidArgumentException('non-nullable clientId cannot be null');
        }
        $this->container['clientId'] = $clientId;

        return $this;
    }

    /**
     * Gets redirectUri
     *
     * @return string
     */
    public function getRedirectUri()
    {
        return $this->container['redirectUri'];
    }

    /**
     * Sets redirectUri
     *
     * @param string $redirectUri Redirection URI to return the authorization code
     *
     * @return self
     */
    public function setRedirectUri($redirectUri)
    {
        if (is_null($redirectUri)) {
            throw new \InvalidArgumentException('non-nullable redirectUri cannot be null');
        }
        $this->container['redirectUri'] = $redirectUri;

        return $this;
    }

    /**
     * Gets projectId
     *
     * @return string
     */
    public function getProjectId()
    {
        return $this->container['projectId'];
    }

    /**
     * Sets projectId
     *
     * @param string $projectId Selected Project UUID that client will be authorized to access
     *
     * @return self
     */
    public function setProjectId($projectId)
    {
        if (is_null($projectId)) {
            throw new \InvalidArgumentException('non-nullable projectId cannot be null');
        }
        $this->container['projectId'] = $projectId;

        return $this;
    }

    /**
     * Gets codeChallenge
     *
     * @return string
     */
    public function getCodeChallenge()
    {
        return $this->container['codeChallenge'];
    }

    /**
     * Sets codeChallenge
     *
     * @param string $codeChallenge PKCE code challenge string (RFC 7636)
     *
     * @return self
     */
    public function setCodeChallenge($codeChallenge)
    {
        if (is_null($codeChallenge)) {
            throw new \InvalidArgumentException('non-nullable codeChallenge cannot be null');
        }
        $this->container['codeChallenge'] = $codeChallenge;

        return $this;
    }

    /**
     * Gets codeChallengeMethod
     *
     * @return string|null
     */
    public function getCodeChallengeMethod()
    {
        return $this->container['codeChallengeMethod'];
    }

    /**
     * Sets codeChallengeMethod
     *
     * @param string|null $codeChallengeMethod PKCE challenge transformation method
     *
     * @return self
     */
    public function setCodeChallengeMethod($codeChallengeMethod)
    {
        if (is_null($codeChallengeMethod)) {
            throw new \InvalidArgumentException('non-nullable codeChallengeMethod cannot be null');
        }
        $allowedValues = $this->getCodeChallengeMethodAllowableValues();
        if (!in_array($codeChallengeMethod, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'codeChallengeMethod', must be one of '%s'",
                    $codeChallengeMethod,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['codeChallengeMethod'] = $codeChallengeMethod;

        return $this;
    }

    /**
     * Gets scopes
     *
     * @return string[]|null
     */
    public function getScopes()
    {
        return $this->container['scopes'];
    }

    /**
     * Sets scopes
     *
     * @param string[]|null $scopes Authorized scope strings
     *
     * @return self
     */
    public function setScopes($scopes)
    {
        if (is_null($scopes)) {
            throw new \InvalidArgumentException('non-nullable scopes cannot be null');
        }
        $this->container['scopes'] = $scopes;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string|null
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string|null $state Opaque client state parameter for CSRF mitigation
     *
     * @return self
     */
    public function setState($state)
    {
        if (is_null($state)) {
            array_push($this->openAPINullablesSetToNull, 'state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['state'] = $state;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


