<?php
/**
 * BiSchemaField
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Omnismith\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnismith API
 *
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.13
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Omnismith\Sdk\Model;

use \ArrayAccess;
use \Omnismith\Sdk\ObjectSerializer;

/**
 * BiSchemaField Class Doc Comment
 *
 * @category Class
 * @description Connector-friendly field definition for BI datasets
 * @package  Omnismith\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BiSchemaField implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'BiSchemaField';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'templateId' => 'string',
        'templateName' => 'string',
        'columnName' => 'string',
        'label' => 'string',
        'source' => 'string',
        'attributeId' => 'string',
        'attributeName' => 'string',
        'attributeType' => 'string',
        'dataType' => 'string',
        'referenceTargetTemplateId' => 'string',
        'referenceTargetAttributeId' => 'string',
        'listOptions' => '\Omnismith\Sdk\Model\BiFieldOption[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'templateId' => 'uuid',
        'templateName' => null,
        'columnName' => null,
        'label' => null,
        'source' => null,
        'attributeId' => 'uuid',
        'attributeName' => null,
        'attributeType' => null,
        'dataType' => null,
        'referenceTargetTemplateId' => 'uuid',
        'referenceTargetAttributeId' => 'uuid',
        'listOptions' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'templateId' => false,
        'templateName' => false,
        'columnName' => false,
        'label' => false,
        'source' => false,
        'attributeId' => true,
        'attributeName' => true,
        'attributeType' => true,
        'dataType' => false,
        'referenceTargetTemplateId' => true,
        'referenceTargetAttributeId' => true,
        'listOptions' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'templateId' => 'template_id',
        'templateName' => 'template_name',
        'columnName' => 'column_name',
        'label' => 'label',
        'source' => 'source',
        'attributeId' => 'attribute_id',
        'attributeName' => 'attribute_name',
        'attributeType' => 'attribute_type',
        'dataType' => 'data_type',
        'referenceTargetTemplateId' => 'reference_target_template_id',
        'referenceTargetAttributeId' => 'reference_target_attribute_id',
        'listOptions' => 'list_options'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'templateId' => 'setTemplateId',
        'templateName' => 'setTemplateName',
        'columnName' => 'setColumnName',
        'label' => 'setLabel',
        'source' => 'setSource',
        'attributeId' => 'setAttributeId',
        'attributeName' => 'setAttributeName',
        'attributeType' => 'setAttributeType',
        'dataType' => 'setDataType',
        'referenceTargetTemplateId' => 'setReferenceTargetTemplateId',
        'referenceTargetAttributeId' => 'setReferenceTargetAttributeId',
        'listOptions' => 'setListOptions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'templateId' => 'getTemplateId',
        'templateName' => 'getTemplateName',
        'columnName' => 'getColumnName',
        'label' => 'getLabel',
        'source' => 'getSource',
        'attributeId' => 'getAttributeId',
        'attributeName' => 'getAttributeName',
        'attributeType' => 'getAttributeType',
        'dataType' => 'getDataType',
        'referenceTargetTemplateId' => 'getReferenceTargetTemplateId',
        'referenceTargetAttributeId' => 'getReferenceTargetAttributeId',
        'listOptions' => 'getListOptions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SOURCE_SYSTEM = 'system';
    public const SOURCE_ATTRIBUTE = 'attribute';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSourceAllowableValues()
    {
        return [
            self::SOURCE_SYSTEM,
            self::SOURCE_ATTRIBUTE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('templateId', $data ?? [], null);
        $this->setIfExists('templateName', $data ?? [], null);
        $this->setIfExists('columnName', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('attributeId', $data ?? [], null);
        $this->setIfExists('attributeName', $data ?? [], null);
        $this->setIfExists('attributeType', $data ?? [], null);
        $this->setIfExists('dataType', $data ?? [], null);
        $this->setIfExists('referenceTargetTemplateId', $data ?? [], null);
        $this->setIfExists('referenceTargetAttributeId', $data ?? [], null);
        $this->setIfExists('listOptions', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getSourceAllowableValues();
        if (!is_null($this->container['source']) && !in_array($this->container['source'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'source', must be one of '%s'",
                $this->container['source'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets templateId
     *
     * @return string|null
     */
    public function getTemplateId()
    {
        return $this->container['templateId'];
    }

    /**
     * Sets templateId
     *
     * @param string|null $templateId Template UUID to which this field belongs
     *
     * @return self
     */
    public function setTemplateId($templateId)
    {
        if (is_null($templateId)) {
            throw new \InvalidArgumentException('non-nullable templateId cannot be null');
        }
        $this->container['templateId'] = $templateId;

        return $this;
    }

    /**
     * Gets templateName
     *
     * @return string|null
     */
    public function getTemplateName()
    {
        return $this->container['templateName'];
    }

    /**
     * Sets templateName
     *
     * @param string|null $templateName Display name of the template schema
     *
     * @return self
     */
    public function setTemplateName($templateName)
    {
        if (is_null($templateName)) {
            throw new \InvalidArgumentException('non-nullable templateName cannot be null');
        }
        $this->container['templateName'] = $templateName;

        return $this;
    }

    /**
     * Gets columnName
     *
     * @return string|null
     */
    public function getColumnName()
    {
        return $this->container['columnName'];
    }

    /**
     * Sets columnName
     *
     * @param string|null $columnName Sanitized SQL-friendly column identifier for BI connectors
     *
     * @return self
     */
    public function setColumnName($columnName)
    {
        if (is_null($columnName)) {
            throw new \InvalidArgumentException('non-nullable columnName cannot be null');
        }
        $this->container['columnName'] = $columnName;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string|null $label Human-readable column header label
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source Field origin (\"system\" for metadata columns, \"attribute\" for dynamic template attributes)
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            throw new \InvalidArgumentException('non-nullable source cannot be null');
        }
        $allowedValues = $this->getSourceAllowableValues();
        if (!in_array($source, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'source', must be one of '%s'",
                    $source,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets attributeId
     *
     * @return string|null
     */
    public function getAttributeId()
    {
        return $this->container['attributeId'];
    }

    /**
     * Sets attributeId
     *
     * @param string|null $attributeId Attribute definition UUID if source is attribute
     *
     * @return self
     */
    public function setAttributeId($attributeId)
    {
        if (is_null($attributeId)) {
            array_push($this->openAPINullablesSetToNull, 'attributeId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attributeId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['attributeId'] = $attributeId;

        return $this;
    }

    /**
     * Gets attributeName
     *
     * @return string|null
     */
    public function getAttributeName()
    {
        return $this->container['attributeName'];
    }

    /**
     * Sets attributeName
     *
     * @param string|null $attributeName Display name of the attribute definition
     *
     * @return self
     */
    public function setAttributeName($attributeName)
    {
        if (is_null($attributeName)) {
            array_push($this->openAPINullablesSetToNull, 'attributeName');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attributeName', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['attributeName'] = $attributeName;

        return $this;
    }

    /**
     * Gets attributeType
     *
     * @return string|null
     */
    public function getAttributeType()
    {
        return $this->container['attributeType'];
    }

    /**
     * Sets attributeType
     *
     * @param string|null $attributeType Kind of dynamic attribute (dimension, metric, list, reference)
     *
     * @return self
     */
    public function setAttributeType($attributeType)
    {
        if (is_null($attributeType)) {
            array_push($this->openAPINullablesSetToNull, 'attributeType');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('attributeType', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['attributeType'] = $attributeType;

        return $this;
    }

    /**
     * Gets dataType
     *
     * @return string|null
     */
    public function getDataType()
    {
        return $this->container['dataType'];
    }

    /**
     * Sets dataType
     *
     * @param string|null $dataType Canonical data type mapping for BI tooling (string, number, boolean, datetime, date)
     *
     * @return self
     */
    public function setDataType($dataType)
    {
        if (is_null($dataType)) {
            throw new \InvalidArgumentException('non-nullable dataType cannot be null');
        }
        $this->container['dataType'] = $dataType;

        return $this;
    }

    /**
     * Gets referenceTargetTemplateId
     *
     * @return string|null
     */
    public function getReferenceTargetTemplateId()
    {
        return $this->container['referenceTargetTemplateId'];
    }

    /**
     * Sets referenceTargetTemplateId
     *
     * @param string|null $referenceTargetTemplateId Target template UUID if this is a reference attribute
     *
     * @return self
     */
    public function setReferenceTargetTemplateId($referenceTargetTemplateId)
    {
        if (is_null($referenceTargetTemplateId)) {
            array_push($this->openAPINullablesSetToNull, 'referenceTargetTemplateId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('referenceTargetTemplateId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['referenceTargetTemplateId'] = $referenceTargetTemplateId;

        return $this;
    }

    /**
     * Gets referenceTargetAttributeId
     *
     * @return string|null
     */
    public function getReferenceTargetAttributeId()
    {
        return $this->container['referenceTargetAttributeId'];
    }

    /**
     * Sets referenceTargetAttributeId
     *
     * @param string|null $referenceTargetAttributeId Target display attribute UUID if this is a reference attribute
     *
     * @return self
     */
    public function setReferenceTargetAttributeId($referenceTargetAttributeId)
    {
        if (is_null($referenceTargetAttributeId)) {
            array_push($this->openAPINullablesSetToNull, 'referenceTargetAttributeId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('referenceTargetAttributeId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['referenceTargetAttributeId'] = $referenceTargetAttributeId;

        return $this;
    }

    /**
     * Gets listOptions
     *
     * @return \Omnismith\Sdk\Model\BiFieldOption[]|null
     */
    public function getListOptions()
    {
        return $this->container['listOptions'];
    }

    /**
     * Sets listOptions
     *
     * @param \Omnismith\Sdk\Model\BiFieldOption[]|null $listOptions Allowed selectable options if this is a list attribute
     *
     * @return self
     */
    public function setListOptions($listOptions)
    {
        if (is_null($listOptions)) {
            throw new \InvalidArgumentException('non-nullable listOptions cannot be null');
        }
        $this->container['listOptions'] = $listOptions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


