<?php
/**
 * TierResponseFeatures
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Omnismith
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnismith API
 *
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Omnismith\Model;

use \ArrayAccess;
use \Omnismith\ObjectSerializer;

/**
 * TierResponseFeatures Class Doc Comment
 *
 * @category Class
 * @package  Omnismith
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TierResponseFeatures implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'TierResponse_features';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'api_access' => 'bool',
        'export_to_csv' => 'bool',
        'sso_enabled' => 'bool',
        'audit_logs' => 'bool',
        'history_retention_days' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'api_access' => null,
        'export_to_csv' => null,
        'sso_enabled' => null,
        'audit_logs' => null,
        'history_retention_days' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'api_access' => false,
        'export_to_csv' => false,
        'sso_enabled' => false,
        'audit_logs' => false,
        'history_retention_days' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'api_access' => 'api_access',
        'export_to_csv' => 'export_to_csv',
        'sso_enabled' => 'sso_enabled',
        'audit_logs' => 'audit_logs',
        'history_retention_days' => 'history_retention_days'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'api_access' => 'setApiAccess',
        'export_to_csv' => 'setExportToCsv',
        'sso_enabled' => 'setSsoEnabled',
        'audit_logs' => 'setAuditLogs',
        'history_retention_days' => 'setHistoryRetentionDays'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'api_access' => 'getApiAccess',
        'export_to_csv' => 'getExportToCsv',
        'sso_enabled' => 'getSsoEnabled',
        'audit_logs' => 'getAuditLogs',
        'history_retention_days' => 'getHistoryRetentionDays'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('api_access', $data ?? [], null);
        $this->setIfExists('export_to_csv', $data ?? [], null);
        $this->setIfExists('sso_enabled', $data ?? [], null);
        $this->setIfExists('audit_logs', $data ?? [], null);
        $this->setIfExists('history_retention_days', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets api_access
     *
     * @return bool|null
     */
    public function getApiAccess()
    {
        return $this->container['api_access'];
    }

    /**
     * Sets api_access
     *
     * @param bool|null $api_access api_access
     *
     * @return self
     */
    public function setApiAccess($api_access)
    {
        if (is_null($api_access)) {
            throw new \InvalidArgumentException('non-nullable api_access cannot be null');
        }
        $this->container['api_access'] = $api_access;

        return $this;
    }

    /**
     * Gets export_to_csv
     *
     * @return bool|null
     */
    public function getExportToCsv()
    {
        return $this->container['export_to_csv'];
    }

    /**
     * Sets export_to_csv
     *
     * @param bool|null $export_to_csv export_to_csv
     *
     * @return self
     */
    public function setExportToCsv($export_to_csv)
    {
        if (is_null($export_to_csv)) {
            throw new \InvalidArgumentException('non-nullable export_to_csv cannot be null');
        }
        $this->container['export_to_csv'] = $export_to_csv;

        return $this;
    }

    /**
     * Gets sso_enabled
     *
     * @return bool|null
     */
    public function getSsoEnabled()
    {
        return $this->container['sso_enabled'];
    }

    /**
     * Sets sso_enabled
     *
     * @param bool|null $sso_enabled sso_enabled
     *
     * @return self
     */
    public function setSsoEnabled($sso_enabled)
    {
        if (is_null($sso_enabled)) {
            throw new \InvalidArgumentException('non-nullable sso_enabled cannot be null');
        }
        $this->container['sso_enabled'] = $sso_enabled;

        return $this;
    }

    /**
     * Gets audit_logs
     *
     * @return bool|null
     */
    public function getAuditLogs()
    {
        return $this->container['audit_logs'];
    }

    /**
     * Sets audit_logs
     *
     * @param bool|null $audit_logs audit_logs
     *
     * @return self
     */
    public function setAuditLogs($audit_logs)
    {
        if (is_null($audit_logs)) {
            throw new \InvalidArgumentException('non-nullable audit_logs cannot be null');
        }
        $this->container['audit_logs'] = $audit_logs;

        return $this;
    }

    /**
     * Gets history_retention_days
     *
     * @return int|null
     */
    public function getHistoryRetentionDays()
    {
        return $this->container['history_retention_days'];
    }

    /**
     * Sets history_retention_days
     *
     * @param int|null $history_retention_days history_retention_days
     *
     * @return self
     */
    public function setHistoryRetentionDays($history_retention_days)
    {
        if (is_null($history_retention_days)) {
            throw new \InvalidArgumentException('non-nullable history_retention_days cannot be null');
        }
        $this->container['history_retention_days'] = $history_retention_days;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


