<?php
/**
 * UpdateDashboardRequestConfig
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Omnismith\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnismith API
 *
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.12
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Omnismith\Sdk\Model;

use \ArrayAccess;
use \Omnismith\Sdk\ObjectSerializer;

/**
 * UpdateDashboardRequestConfig Class Doc Comment
 *
 * @category Class
 * @description Updated dashboard canvas (minCols: 12, maxCols: 12) and auto-refresh configuration
 * @package  Omnismith\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateDashboardRequestConfig implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'UpdateDashboardRequest_config';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'minCols' => 'int',
        'maxCols' => 'int',
        'minRows' => 'int',
        'maxRows' => 'int',
        'autoRefresh' => 'int',
        'thumbnail' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'minCols' => null,
        'maxCols' => null,
        'minRows' => null,
        'maxRows' => null,
        'autoRefresh' => null,
        'thumbnail' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'minCols' => false,
        'maxCols' => false,
        'minRows' => false,
        'maxRows' => false,
        'autoRefresh' => false,
        'thumbnail' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'minCols' => 'minCols',
        'maxCols' => 'maxCols',
        'minRows' => 'minRows',
        'maxRows' => 'maxRows',
        'autoRefresh' => 'auto_refresh',
        'thumbnail' => 'thumbnail'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'minCols' => 'setMinCols',
        'maxCols' => 'setMaxCols',
        'minRows' => 'setMinRows',
        'maxRows' => 'setMaxRows',
        'autoRefresh' => 'setAutoRefresh',
        'thumbnail' => 'setThumbnail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'minCols' => 'getMinCols',
        'maxCols' => 'getMaxCols',
        'minRows' => 'getMinRows',
        'maxRows' => 'getMaxRows',
        'autoRefresh' => 'getAutoRefresh',
        'thumbnail' => 'getThumbnail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('minCols', $data ?? [], 12);
        $this->setIfExists('maxCols', $data ?? [], 12);
        $this->setIfExists('minRows', $data ?? [], 1);
        $this->setIfExists('maxRows', $data ?? [], 100);
        $this->setIfExists('autoRefresh', $data ?? [], 0);
        $this->setIfExists('thumbnail', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets minCols
     *
     * @return int|null
     */
    public function getMinCols()
    {
        return $this->container['minCols'];
    }

    /**
     * Sets minCols
     *
     * @param int|null $minCols Minimum number of grid columns (standard: 12)
     *
     * @return self
     */
    public function setMinCols($minCols)
    {
        if (is_null($minCols)) {
            throw new \InvalidArgumentException('non-nullable minCols cannot be null');
        }
        $this->container['minCols'] = $minCols;

        return $this;
    }

    /**
     * Gets maxCols
     *
     * @return int|null
     */
    public function getMaxCols()
    {
        return $this->container['maxCols'];
    }

    /**
     * Sets maxCols
     *
     * @param int|null $maxCols Maximum number of grid columns (standard: 12)
     *
     * @return self
     */
    public function setMaxCols($maxCols)
    {
        if (is_null($maxCols)) {
            throw new \InvalidArgumentException('non-nullable maxCols cannot be null');
        }
        $this->container['maxCols'] = $maxCols;

        return $this;
    }

    /**
     * Gets minRows
     *
     * @return int|null
     */
    public function getMinRows()
    {
        return $this->container['minRows'];
    }

    /**
     * Sets minRows
     *
     * @param int|null $minRows Minimum number of grid rows (standard: 1)
     *
     * @return self
     */
    public function setMinRows($minRows)
    {
        if (is_null($minRows)) {
            throw new \InvalidArgumentException('non-nullable minRows cannot be null');
        }
        $this->container['minRows'] = $minRows;

        return $this;
    }

    /**
     * Gets maxRows
     *
     * @return int|null
     */
    public function getMaxRows()
    {
        return $this->container['maxRows'];
    }

    /**
     * Sets maxRows
     *
     * @param int|null $maxRows Maximum number of grid rows (standard: 100)
     *
     * @return self
     */
    public function setMaxRows($maxRows)
    {
        if (is_null($maxRows)) {
            throw new \InvalidArgumentException('non-nullable maxRows cannot be null');
        }
        $this->container['maxRows'] = $maxRows;

        return $this;
    }

    /**
     * Gets autoRefresh
     *
     * @return int|null
     */
    public function getAutoRefresh()
    {
        return $this->container['autoRefresh'];
    }

    /**
     * Sets autoRefresh
     *
     * @param int|null $autoRefresh Auto-refresh interval in seconds (0 = off, 30, 60, 300)
     *
     * @return self
     */
    public function setAutoRefresh($autoRefresh)
    {
        if (is_null($autoRefresh)) {
            throw new \InvalidArgumentException('non-nullable autoRefresh cannot be null');
        }
        $this->container['autoRefresh'] = $autoRefresh;

        return $this;
    }

    /**
     * Gets thumbnail
     *
     * @return string|null
     */
    public function getThumbnail()
    {
        return $this->container['thumbnail'];
    }

    /**
     * Sets thumbnail
     *
     * @param string|null $thumbnail Base64 data URL preview thumbnail of the dashboard canvas
     *
     * @return self
     */
    public function setThumbnail($thumbnail)
    {
        if (is_null($thumbnail)) {
            array_push($this->openAPINullablesSetToNull, 'thumbnail');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('thumbnail', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['thumbnail'] = $thumbnail;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


