<?php
/**
 * BIApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Omnismith\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnismith API
 *
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.14
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Omnismith\Sdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Omnismith\Sdk\ApiException;
use Omnismith\Sdk\Configuration;
use Omnismith\Sdk\FormDataProcessor;
use Omnismith\Sdk\HeaderSelector;
use Omnismith\Sdk\ObjectSerializer;

/**
 * BIApi Class Doc Comment
 *
 * @category Class
 * @package  Omnismith\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BIApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getBiSchema' => [
            'application/json',
        ],
        'listBiTemplateRows' => [
            'application/json',
        ],
        'listBiTemplateTimeSeries' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getBiSchema
     *
     * Get BI schema catalog
     *
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBiSchema'] to see the possible values for this operation
     *
     * @throws \Omnismith\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Omnismith\Sdk\Model\BiSchemaResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse
     */
    public function getBiSchema($xOmnismithProjectId = null, string $contentType = self::contentTypes['getBiSchema'][0])
    {
        list($response) = $this->getBiSchemaWithHttpInfo($xOmnismithProjectId, $contentType);
        return $response;
    }

    /**
     * Operation getBiSchemaWithHttpInfo
     *
     * Get BI schema catalog
     *
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBiSchema'] to see the possible values for this operation
     *
     * @throws \Omnismith\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Omnismith\Sdk\Model\BiSchemaResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBiSchemaWithHttpInfo($xOmnismithProjectId = null, string $contentType = self::contentTypes['getBiSchema'][0])
    {
        $request = $this->getBiSchemaRequest($xOmnismithProjectId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\BiSchemaResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Omnismith\Sdk\Model\BiSchemaResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\BiSchemaResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getBiSchemaAsync
     *
     * Get BI schema catalog
     *
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBiSchema'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBiSchemaAsync($xOmnismithProjectId = null, string $contentType = self::contentTypes['getBiSchema'][0])
    {
        return $this->getBiSchemaAsyncWithHttpInfo($xOmnismithProjectId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBiSchemaAsyncWithHttpInfo
     *
     * Get BI schema catalog
     *
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBiSchema'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBiSchemaAsyncWithHttpInfo($xOmnismithProjectId = null, string $contentType = self::contentTypes['getBiSchema'][0])
    {
        $returnType = '\Omnismith\Sdk\Model\BiSchemaResponse';
        $request = $this->getBiSchemaRequest($xOmnismithProjectId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBiSchema'
     *
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getBiSchema'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getBiSchemaRequest($xOmnismithProjectId = null, string $contentType = self::contentTypes['getBiSchema'][0])
    {



        $resourcePath = '/bi/schema';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($xOmnismithProjectId !== null) {
            $headerParams['X-Omnismith-Project-Id'] = ObjectSerializer::toHeaderValue($xOmnismithProjectId);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listBiTemplateRows
     *
     * List flattened template rows for BI integration
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema to query (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  int|null $limit Maximum number of rows to return per page (1-100) (optional, default to 50)
     * @param  int|null $offset Zero-based pagination offset (optional, default to 0)
     * @param  string|null $sortField Attribute UUID, slug, or standard field (id, created_at, updated_at, deleted_at) to sort by (optional)
     * @param  string|null $sortDirection Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending) (optional, default to 'asc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateRows'] to see the possible values for this operation
     *
     * @throws \Omnismith\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Omnismith\Sdk\Model\BiTemplateRowsResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ValidationErrorResponse|\Omnismith\Sdk\Model\ErrorResponse
     */
    public function listBiTemplateRows($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $limit = 50, $offset = 0, $sortField = null, $sortDirection = 'asc', string $contentType = self::contentTypes['listBiTemplateRows'][0])
    {
        list($response) = $this->listBiTemplateRowsWithHttpInfo($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId, $limit, $offset, $sortField, $sortDirection, $contentType);
        return $response;
    }

    /**
     * Operation listBiTemplateRowsWithHttpInfo
     *
     * List flattened template rows for BI integration
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema to query (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  int|null $limit Maximum number of rows to return per page (1-100) (optional, default to 50)
     * @param  int|null $offset Zero-based pagination offset (optional, default to 0)
     * @param  string|null $sortField Attribute UUID, slug, or standard field (id, created_at, updated_at, deleted_at) to sort by (optional)
     * @param  string|null $sortDirection Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending) (optional, default to 'asc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateRows'] to see the possible values for this operation
     *
     * @throws \Omnismith\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Omnismith\Sdk\Model\BiTemplateRowsResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ValidationErrorResponse|\Omnismith\Sdk\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listBiTemplateRowsWithHttpInfo($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $limit = 50, $offset = 0, $sortField = null, $sortDirection = 'asc', string $contentType = self::contentTypes['listBiTemplateRows'][0])
    {
        $request = $this->listBiTemplateRowsRequest($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId, $limit, $offset, $sortField, $sortDirection, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\BiTemplateRowsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ValidationErrorResponse',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Omnismith\Sdk\Model\BiTemplateRowsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\BiTemplateRowsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ValidationErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listBiTemplateRowsAsync
     *
     * List flattened template rows for BI integration
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema to query (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  int|null $limit Maximum number of rows to return per page (1-100) (optional, default to 50)
     * @param  int|null $offset Zero-based pagination offset (optional, default to 0)
     * @param  string|null $sortField Attribute UUID, slug, or standard field (id, created_at, updated_at, deleted_at) to sort by (optional)
     * @param  string|null $sortDirection Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending) (optional, default to 'asc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateRows'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listBiTemplateRowsAsync($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $limit = 50, $offset = 0, $sortField = null, $sortDirection = 'asc', string $contentType = self::contentTypes['listBiTemplateRows'][0])
    {
        return $this->listBiTemplateRowsAsyncWithHttpInfo($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId, $limit, $offset, $sortField, $sortDirection, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listBiTemplateRowsAsyncWithHttpInfo
     *
     * List flattened template rows for BI integration
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema to query (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  int|null $limit Maximum number of rows to return per page (1-100) (optional, default to 50)
     * @param  int|null $offset Zero-based pagination offset (optional, default to 0)
     * @param  string|null $sortField Attribute UUID, slug, or standard field (id, created_at, updated_at, deleted_at) to sort by (optional)
     * @param  string|null $sortDirection Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending) (optional, default to 'asc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateRows'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listBiTemplateRowsAsyncWithHttpInfo($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $limit = 50, $offset = 0, $sortField = null, $sortDirection = 'asc', string $contentType = self::contentTypes['listBiTemplateRows'][0])
    {
        $returnType = '\Omnismith\Sdk\Model\BiTemplateRowsResponse';
        $request = $this->listBiTemplateRowsRequest($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId, $limit, $offset, $sortField, $sortDirection, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listBiTemplateRows'
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema to query (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  int|null $limit Maximum number of rows to return per page (1-100) (optional, default to 50)
     * @param  int|null $offset Zero-based pagination offset (optional, default to 0)
     * @param  string|null $sortField Attribute UUID, slug, or standard field (id, created_at, updated_at, deleted_at) to sort by (optional)
     * @param  string|null $sortDirection Sort direction: \&quot;asc\&quot; (ascending) or \&quot;desc\&quot; (descending) (optional, default to 'asc')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateRows'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listBiTemplateRowsRequest($templateId, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $limit = 50, $offset = 0, $sortField = null, $sortDirection = 'asc', string $contentType = self::contentTypes['listBiTemplateRows'][0])
    {

        // verify the required parameter 'templateId' is set
        if ($templateId === null || (is_array($templateId) && count($templateId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $templateId when calling listBiTemplateRows'
            );
        }

        // verify the required parameter 'biListTemplateRowsRequest' is set
        if ($biListTemplateRowsRequest === null || (is_array($biListTemplateRowsRequest) && count($biListTemplateRowsRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $biListTemplateRowsRequest when calling listBiTemplateRows'
            );
        }


        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling BIApi.listBiTemplateRows, must be smaller than or equal to 100.');
        }
        




        $resourcePath = '/bi/templates/{template_id}/rows';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sortField,
            'sort_field', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sortDirection,
            'sort_direction', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($xOmnismithProjectId !== null) {
            $headerParams['X-Omnismith-Project-Id'] = ObjectSerializer::toHeaderValue($xOmnismithProjectId);
        }

        // path params
        if ($templateId !== null) {
            $resourcePath = str_replace(
                '{' . 'template_id' . '}',
                ObjectSerializer::toPathValue($templateId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($biListTemplateRowsRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($biListTemplateRowsRequest));
            } else {
                $httpBody = $biListTemplateRowsRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listBiTemplateTimeSeries
     *
     * List aggregated time-series rows for BI integration
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema (required)
     * @param  string $attributeIds Comma-separated metric attribute UUIDs to aggregate (required)
     * @param  int $start Start timestamp as Unix epoch in seconds (required)
     * @param  int $end End timestamp as Unix epoch in seconds (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string|null $aggregateFunc Aggregation function applied within each time bucket (optional, default to 'avg')
     * @param  string|null $bucketWidth Time bucket width interval (e.g. 1 minute, 5 minutes, 1 hour, 1 day) (optional, default to '1 hour')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateTimeSeries'] to see the possible values for this operation
     *
     * @throws \Omnismith\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Omnismith\Sdk\Model\BiTimeSeriesResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ValidationErrorResponse|\Omnismith\Sdk\Model\ErrorResponse
     */
    public function listBiTemplateTimeSeries($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $aggregateFunc = 'avg', $bucketWidth = '1 hour', string $contentType = self::contentTypes['listBiTemplateTimeSeries'][0])
    {
        list($response) = $this->listBiTemplateTimeSeriesWithHttpInfo($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId, $aggregateFunc, $bucketWidth, $contentType);
        return $response;
    }

    /**
     * Operation listBiTemplateTimeSeriesWithHttpInfo
     *
     * List aggregated time-series rows for BI integration
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema (required)
     * @param  string $attributeIds Comma-separated metric attribute UUIDs to aggregate (required)
     * @param  int $start Start timestamp as Unix epoch in seconds (required)
     * @param  int $end End timestamp as Unix epoch in seconds (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string|null $aggregateFunc Aggregation function applied within each time bucket (optional, default to 'avg')
     * @param  string|null $bucketWidth Time bucket width interval (e.g. 1 minute, 5 minutes, 1 hour, 1 day) (optional, default to '1 hour')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateTimeSeries'] to see the possible values for this operation
     *
     * @throws \Omnismith\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Omnismith\Sdk\Model\BiTimeSeriesResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ErrorResponse|\Omnismith\Sdk\Model\ValidationErrorResponse|\Omnismith\Sdk\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function listBiTemplateTimeSeriesWithHttpInfo($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $aggregateFunc = 'avg', $bucketWidth = '1 hour', string $contentType = self::contentTypes['listBiTemplateTimeSeries'][0])
    {
        $request = $this->listBiTemplateTimeSeriesRequest($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId, $aggregateFunc, $bucketWidth, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\BiTimeSeriesResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ValidationErrorResponse',
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Omnismith\Sdk\Model\BiTimeSeriesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\BiTimeSeriesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ValidationErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Sdk\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listBiTemplateTimeSeriesAsync
     *
     * List aggregated time-series rows for BI integration
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema (required)
     * @param  string $attributeIds Comma-separated metric attribute UUIDs to aggregate (required)
     * @param  int $start Start timestamp as Unix epoch in seconds (required)
     * @param  int $end End timestamp as Unix epoch in seconds (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string|null $aggregateFunc Aggregation function applied within each time bucket (optional, default to 'avg')
     * @param  string|null $bucketWidth Time bucket width interval (e.g. 1 minute, 5 minutes, 1 hour, 1 day) (optional, default to '1 hour')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateTimeSeries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listBiTemplateTimeSeriesAsync($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $aggregateFunc = 'avg', $bucketWidth = '1 hour', string $contentType = self::contentTypes['listBiTemplateTimeSeries'][0])
    {
        return $this->listBiTemplateTimeSeriesAsyncWithHttpInfo($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId, $aggregateFunc, $bucketWidth, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listBiTemplateTimeSeriesAsyncWithHttpInfo
     *
     * List aggregated time-series rows for BI integration
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema (required)
     * @param  string $attributeIds Comma-separated metric attribute UUIDs to aggregate (required)
     * @param  int $start Start timestamp as Unix epoch in seconds (required)
     * @param  int $end End timestamp as Unix epoch in seconds (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string|null $aggregateFunc Aggregation function applied within each time bucket (optional, default to 'avg')
     * @param  string|null $bucketWidth Time bucket width interval (e.g. 1 minute, 5 minutes, 1 hour, 1 day) (optional, default to '1 hour')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateTimeSeries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listBiTemplateTimeSeriesAsyncWithHttpInfo($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $aggregateFunc = 'avg', $bucketWidth = '1 hour', string $contentType = self::contentTypes['listBiTemplateTimeSeries'][0])
    {
        $returnType = '\Omnismith\Sdk\Model\BiTimeSeriesResponse';
        $request = $this->listBiTemplateTimeSeriesRequest($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId, $aggregateFunc, $bucketWidth, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listBiTemplateTimeSeries'
     *
     * @param  string $templateId Unique identifier (UUID) of the template schema (required)
     * @param  string $attributeIds Comma-separated metric attribute UUIDs to aggregate (required)
     * @param  int $start Start timestamp as Unix epoch in seconds (required)
     * @param  int $end End timestamp as Unix epoch in seconds (required)
     * @param  \Omnismith\Sdk\Model\BiListTemplateRowsRequest $biListTemplateRowsRequest (required)
     * @param  string|null $xOmnismithProjectId The project this call acts on. A credential proves identity and grants a set of projects; it never selects one, so every tenant-scoped call names its target here. The value must be one of the projects in the credential&#39;s &#x60;projects&#x60; claim and must still be reachable — a project the caller is not a member of, or one that has been deleted, is rejected with 403 rather than silently ignored. A project the caller *is* a member of but which the credential predates is also rejected with 403, carrying the code &#x60;stale_project_grant&#x60;; that one is answered by refreshing the credential once and retrying, and is the only 403 here worth retrying. Omitting the header is not an error: the caller is simply acting with no project selected, and a tenant-scoped operation then answers 409 &#x60;no_project_selected&#x60;. Two clients holding the same credential may send different values at the same time. (optional)
     * @param  string|null $aggregateFunc Aggregation function applied within each time bucket (optional, default to 'avg')
     * @param  string|null $bucketWidth Time bucket width interval (e.g. 1 minute, 5 minutes, 1 hour, 1 day) (optional, default to '1 hour')
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listBiTemplateTimeSeries'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listBiTemplateTimeSeriesRequest($templateId, $attributeIds, $start, $end, $biListTemplateRowsRequest, $xOmnismithProjectId = null, $aggregateFunc = 'avg', $bucketWidth = '1 hour', string $contentType = self::contentTypes['listBiTemplateTimeSeries'][0])
    {

        // verify the required parameter 'templateId' is set
        if ($templateId === null || (is_array($templateId) && count($templateId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $templateId when calling listBiTemplateTimeSeries'
            );
        }

        // verify the required parameter 'attributeIds' is set
        if ($attributeIds === null || (is_array($attributeIds) && count($attributeIds) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $attributeIds when calling listBiTemplateTimeSeries'
            );
        }

        // verify the required parameter 'start' is set
        if ($start === null || (is_array($start) && count($start) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $start when calling listBiTemplateTimeSeries'
            );
        }

        // verify the required parameter 'end' is set
        if ($end === null || (is_array($end) && count($end) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $end when calling listBiTemplateTimeSeries'
            );
        }

        // verify the required parameter 'biListTemplateRowsRequest' is set
        if ($biListTemplateRowsRequest === null || (is_array($biListTemplateRowsRequest) && count($biListTemplateRowsRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $biListTemplateRowsRequest when calling listBiTemplateTimeSeries'
            );
        }





        $resourcePath = '/bi/templates/{template_id}/time-series';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $attributeIds,
            'attribute_ids', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $aggregateFunc,
            'aggregate_func', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $bucketWidth,
            'bucket_width', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $start,
            'start', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $end,
            'end', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);

        // header params
        if ($xOmnismithProjectId !== null) {
            $headerParams['X-Omnismith-Project-Id'] = ObjectSerializer::toHeaderValue($xOmnismithProjectId);
        }

        // path params
        if ($templateId !== null) {
            $resourcePath = str_replace(
                '{' . 'template_id' . '}',
                ObjectSerializer::toPathValue($templateId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($biListTemplateRowsRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($biListTemplateRowsRequest));
            } else {
                $httpBody = $biListTemplateRowsRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
