<?php
/**
 * DashboardBlocksApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Omnismith
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Omnismith API
 *
 * API Documentation for Omnismith
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Omnismith\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Omnismith\ApiException;
use Omnismith\Configuration;
use Omnismith\FormDataProcessor;
use Omnismith\HeaderSelector;
use Omnismith\ObjectSerializer;

/**
 * DashboardBlocksApi Class Doc Comment
 *
 * @category Class
 * @package  Omnismith
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DashboardBlocksApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createDashboardBlock' => [
            'application/json',
        ],
        'deleteDashboardBlock' => [
            'application/json',
        ],
        'getDashboardBlock' => [
            'application/json',
        ],
        'listDashboardBlocks' => [
            'application/json',
        ],
        'resolveDashboardBlock' => [
            'application/json',
        ],
        'updateDashboardBlock' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createDashboardBlock
     *
     * Create a new block in a dashboard
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  \Omnismith\Model\CreateDashboardBlockRequest $create_dashboard_block_request create_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Omnismith\Model\CreateAttributeItem201Response|\Omnismith\Model\ValidationErrorResponse|\Omnismith\Model\ErrorResponse
     */
    public function createDashboardBlock($dashboard_id, $create_dashboard_block_request, string $contentType = self::contentTypes['createDashboardBlock'][0])
    {
        list($response) = $this->createDashboardBlockWithHttpInfo($dashboard_id, $create_dashboard_block_request, $contentType);
        return $response;
    }

    /**
     * Operation createDashboardBlockWithHttpInfo
     *
     * Create a new block in a dashboard
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  \Omnismith\Model\CreateDashboardBlockRequest $create_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Omnismith\Model\CreateAttributeItem201Response|\Omnismith\Model\ValidationErrorResponse|\Omnismith\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createDashboardBlockWithHttpInfo($dashboard_id, $create_dashboard_block_request, string $contentType = self::contentTypes['createDashboardBlock'][0])
    {
        $request = $this->createDashboardBlockRequest($dashboard_id, $create_dashboard_block_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Model\CreateAttributeItem201Response',
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Model\ValidationErrorResponse',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Omnismith\Model\CreateAttributeItem201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Model\CreateAttributeItem201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Model\ValidationErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createDashboardBlockAsync
     *
     * Create a new block in a dashboard
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  \Omnismith\Model\CreateDashboardBlockRequest $create_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createDashboardBlockAsync($dashboard_id, $create_dashboard_block_request, string $contentType = self::contentTypes['createDashboardBlock'][0])
    {
        return $this->createDashboardBlockAsyncWithHttpInfo($dashboard_id, $create_dashboard_block_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createDashboardBlockAsyncWithHttpInfo
     *
     * Create a new block in a dashboard
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  \Omnismith\Model\CreateDashboardBlockRequest $create_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createDashboardBlockAsyncWithHttpInfo($dashboard_id, $create_dashboard_block_request, string $contentType = self::contentTypes['createDashboardBlock'][0])
    {
        $returnType = '\Omnismith\Model\CreateAttributeItem201Response';
        $request = $this->createDashboardBlockRequest($dashboard_id, $create_dashboard_block_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createDashboardBlock'
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  \Omnismith\Model\CreateDashboardBlockRequest $create_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createDashboardBlockRequest($dashboard_id, $create_dashboard_block_request, string $contentType = self::contentTypes['createDashboardBlock'][0])
    {

        // verify the required parameter 'dashboard_id' is set
        if ($dashboard_id === null || (is_array($dashboard_id) && count($dashboard_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dashboard_id when calling createDashboardBlock'
            );
        }

        // verify the required parameter 'create_dashboard_block_request' is set
        if ($create_dashboard_block_request === null || (is_array($create_dashboard_block_request) && count($create_dashboard_block_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_dashboard_block_request when calling createDashboardBlock'
            );
        }


        $resourcePath = '/dashboards/{dashboardId}/blocks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($dashboard_id !== null) {
            $resourcePath = str_replace(
                '{' . 'dashboardId' . '}',
                ObjectSerializer::toPathValue($dashboard_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_dashboard_block_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_dashboard_block_request));
            } else {
                $httpBody = $create_dashboard_block_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteDashboardBlock
     *
     * Delete a dashboard block
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function deleteDashboardBlock($dashboard_id, $block_id, string $contentType = self::contentTypes['deleteDashboardBlock'][0])
    {
        $this->deleteDashboardBlockWithHttpInfo($dashboard_id, $block_id, $contentType);
    }

    /**
     * Operation deleteDashboardBlockWithHttpInfo
     *
     * Delete a dashboard block
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteDashboardBlockWithHttpInfo($dashboard_id, $block_id, string $contentType = self::contentTypes['deleteDashboardBlock'][0])
    {
        $request = $this->deleteDashboardBlockRequest($dashboard_id, $block_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteDashboardBlockAsync
     *
     * Delete a dashboard block
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteDashboardBlockAsync($dashboard_id, $block_id, string $contentType = self::contentTypes['deleteDashboardBlock'][0])
    {
        return $this->deleteDashboardBlockAsyncWithHttpInfo($dashboard_id, $block_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteDashboardBlockAsyncWithHttpInfo
     *
     * Delete a dashboard block
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteDashboardBlockAsyncWithHttpInfo($dashboard_id, $block_id, string $contentType = self::contentTypes['deleteDashboardBlock'][0])
    {
        $returnType = '';
        $request = $this->deleteDashboardBlockRequest($dashboard_id, $block_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteDashboardBlock'
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteDashboardBlockRequest($dashboard_id, $block_id, string $contentType = self::contentTypes['deleteDashboardBlock'][0])
    {

        // verify the required parameter 'dashboard_id' is set
        if ($dashboard_id === null || (is_array($dashboard_id) && count($dashboard_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dashboard_id when calling deleteDashboardBlock'
            );
        }

        // verify the required parameter 'block_id' is set
        if ($block_id === null || (is_array($block_id) && count($block_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $block_id when calling deleteDashboardBlock'
            );
        }


        $resourcePath = '/dashboards/{dashboardId}/blocks/{blockId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($dashboard_id !== null) {
            $resourcePath = str_replace(
                '{' . 'dashboardId' . '}',
                ObjectSerializer::toPathValue($dashboard_id),
                $resourcePath
            );
        }
        // path params
        if ($block_id !== null) {
            $resourcePath = str_replace(
                '{' . 'blockId' . '}',
                ObjectSerializer::toPathValue($block_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDashboardBlock
     *
     * Get a dashboard block by ID
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Omnismith\Model\DashboardBlockResponse
     */
    public function getDashboardBlock($dashboard_id, $block_id, string $contentType = self::contentTypes['getDashboardBlock'][0])
    {
        list($response) = $this->getDashboardBlockWithHttpInfo($dashboard_id, $block_id, $contentType);
        return $response;
    }

    /**
     * Operation getDashboardBlockWithHttpInfo
     *
     * Get a dashboard block by ID
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Omnismith\Model\DashboardBlockResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDashboardBlockWithHttpInfo($dashboard_id, $block_id, string $contentType = self::contentTypes['getDashboardBlock'][0])
    {
        $request = $this->getDashboardBlockRequest($dashboard_id, $block_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Model\DashboardBlockResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Omnismith\Model\DashboardBlockResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Model\DashboardBlockResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getDashboardBlockAsync
     *
     * Get a dashboard block by ID
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDashboardBlockAsync($dashboard_id, $block_id, string $contentType = self::contentTypes['getDashboardBlock'][0])
    {
        return $this->getDashboardBlockAsyncWithHttpInfo($dashboard_id, $block_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDashboardBlockAsyncWithHttpInfo
     *
     * Get a dashboard block by ID
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDashboardBlockAsyncWithHttpInfo($dashboard_id, $block_id, string $contentType = self::contentTypes['getDashboardBlock'][0])
    {
        $returnType = '\Omnismith\Model\DashboardBlockResponse';
        $request = $this->getDashboardBlockRequest($dashboard_id, $block_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDashboardBlock'
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getDashboardBlockRequest($dashboard_id, $block_id, string $contentType = self::contentTypes['getDashboardBlock'][0])
    {

        // verify the required parameter 'dashboard_id' is set
        if ($dashboard_id === null || (is_array($dashboard_id) && count($dashboard_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dashboard_id when calling getDashboardBlock'
            );
        }

        // verify the required parameter 'block_id' is set
        if ($block_id === null || (is_array($block_id) && count($block_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $block_id when calling getDashboardBlock'
            );
        }


        $resourcePath = '/dashboards/{dashboardId}/blocks/{blockId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($dashboard_id !== null) {
            $resourcePath = str_replace(
                '{' . 'dashboardId' . '}',
                ObjectSerializer::toPathValue($dashboard_id),
                $resourcePath
            );
        }
        // path params
        if ($block_id !== null) {
            $resourcePath = str_replace(
                '{' . 'blockId' . '}',
                ObjectSerializer::toPathValue($block_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listDashboardBlocks
     *
     * List all blocks in a dashboard
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDashboardBlocks'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Omnismith\Model\ListDashboardBlocks200Response
     */
    public function listDashboardBlocks($dashboard_id, string $contentType = self::contentTypes['listDashboardBlocks'][0])
    {
        list($response) = $this->listDashboardBlocksWithHttpInfo($dashboard_id, $contentType);
        return $response;
    }

    /**
     * Operation listDashboardBlocksWithHttpInfo
     *
     * List all blocks in a dashboard
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDashboardBlocks'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Omnismith\Model\ListDashboardBlocks200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function listDashboardBlocksWithHttpInfo($dashboard_id, string $contentType = self::contentTypes['listDashboardBlocks'][0])
    {
        $request = $this->listDashboardBlocksRequest($dashboard_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Model\ListDashboardBlocks200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Omnismith\Model\ListDashboardBlocks200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Model\ListDashboardBlocks200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listDashboardBlocksAsync
     *
     * List all blocks in a dashboard
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDashboardBlocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listDashboardBlocksAsync($dashboard_id, string $contentType = self::contentTypes['listDashboardBlocks'][0])
    {
        return $this->listDashboardBlocksAsyncWithHttpInfo($dashboard_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listDashboardBlocksAsyncWithHttpInfo
     *
     * List all blocks in a dashboard
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDashboardBlocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listDashboardBlocksAsyncWithHttpInfo($dashboard_id, string $contentType = self::contentTypes['listDashboardBlocks'][0])
    {
        $returnType = '\Omnismith\Model\ListDashboardBlocks200Response';
        $request = $this->listDashboardBlocksRequest($dashboard_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listDashboardBlocks'
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listDashboardBlocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listDashboardBlocksRequest($dashboard_id, string $contentType = self::contentTypes['listDashboardBlocks'][0])
    {

        // verify the required parameter 'dashboard_id' is set
        if ($dashboard_id === null || (is_array($dashboard_id) && count($dashboard_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dashboard_id when calling listDashboardBlocks'
            );
        }


        $resourcePath = '/dashboards/{dashboardId}/blocks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($dashboard_id !== null) {
            $resourcePath = str_replace(
                '{' . 'dashboardId' . '}',
                ObjectSerializer::toPathValue($dashboard_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation resolveDashboardBlock
     *
     * Resolve a dashboard block to its computed data
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Omnismith\Model\ResolvedBlockResponse
     */
    public function resolveDashboardBlock($dashboard_id, $block_id, string $contentType = self::contentTypes['resolveDashboardBlock'][0])
    {
        list($response) = $this->resolveDashboardBlockWithHttpInfo($dashboard_id, $block_id, $contentType);
        return $response;
    }

    /**
     * Operation resolveDashboardBlockWithHttpInfo
     *
     * Resolve a dashboard block to its computed data
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Omnismith\Model\ResolvedBlockResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function resolveDashboardBlockWithHttpInfo($dashboard_id, $block_id, string $contentType = self::contentTypes['resolveDashboardBlock'][0])
    {
        $request = $this->resolveDashboardBlockRequest($dashboard_id, $block_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Omnismith\Model\ResolvedBlockResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Omnismith\Model\ResolvedBlockResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Model\ResolvedBlockResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation resolveDashboardBlockAsync
     *
     * Resolve a dashboard block to its computed data
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resolveDashboardBlockAsync($dashboard_id, $block_id, string $contentType = self::contentTypes['resolveDashboardBlock'][0])
    {
        return $this->resolveDashboardBlockAsyncWithHttpInfo($dashboard_id, $block_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation resolveDashboardBlockAsyncWithHttpInfo
     *
     * Resolve a dashboard block to its computed data
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function resolveDashboardBlockAsyncWithHttpInfo($dashboard_id, $block_id, string $contentType = self::contentTypes['resolveDashboardBlock'][0])
    {
        $returnType = '\Omnismith\Model\ResolvedBlockResponse';
        $request = $this->resolveDashboardBlockRequest($dashboard_id, $block_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'resolveDashboardBlock'
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['resolveDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function resolveDashboardBlockRequest($dashboard_id, $block_id, string $contentType = self::contentTypes['resolveDashboardBlock'][0])
    {

        // verify the required parameter 'dashboard_id' is set
        if ($dashboard_id === null || (is_array($dashboard_id) && count($dashboard_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dashboard_id when calling resolveDashboardBlock'
            );
        }

        // verify the required parameter 'block_id' is set
        if ($block_id === null || (is_array($block_id) && count($block_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $block_id when calling resolveDashboardBlock'
            );
        }


        $resourcePath = '/dashboards/{dashboardId}/blocks/{blockId}/resolve';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($dashboard_id !== null) {
            $resourcePath = str_replace(
                '{' . 'dashboardId' . '}',
                ObjectSerializer::toPathValue($dashboard_id),
                $resourcePath
            );
        }
        // path params
        if ($block_id !== null) {
            $resourcePath = str_replace(
                '{' . 'blockId' . '}',
                ObjectSerializer::toPathValue($block_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateDashboardBlock
     *
     * Update a dashboard block
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  \Omnismith\Model\UpdateDashboardBlockRequest $update_dashboard_block_request update_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function updateDashboardBlock($dashboard_id, $block_id, $update_dashboard_block_request, string $contentType = self::contentTypes['updateDashboardBlock'][0])
    {
        $this->updateDashboardBlockWithHttpInfo($dashboard_id, $block_id, $update_dashboard_block_request, $contentType);
    }

    /**
     * Operation updateDashboardBlockWithHttpInfo
     *
     * Update a dashboard block
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  \Omnismith\Model\UpdateDashboardBlockRequest $update_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDashboardBlock'] to see the possible values for this operation
     *
     * @throws \Omnismith\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateDashboardBlockWithHttpInfo($dashboard_id, $block_id, $update_dashboard_block_request, string $contentType = self::contentTypes['updateDashboardBlock'][0])
    {
        $request = $this->updateDashboardBlockRequest($dashboard_id, $block_id, $update_dashboard_block_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Omnismith\Model\ValidationErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateDashboardBlockAsync
     *
     * Update a dashboard block
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  \Omnismith\Model\UpdateDashboardBlockRequest $update_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateDashboardBlockAsync($dashboard_id, $block_id, $update_dashboard_block_request, string $contentType = self::contentTypes['updateDashboardBlock'][0])
    {
        return $this->updateDashboardBlockAsyncWithHttpInfo($dashboard_id, $block_id, $update_dashboard_block_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateDashboardBlockAsyncWithHttpInfo
     *
     * Update a dashboard block
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  \Omnismith\Model\UpdateDashboardBlockRequest $update_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateDashboardBlockAsyncWithHttpInfo($dashboard_id, $block_id, $update_dashboard_block_request, string $contentType = self::contentTypes['updateDashboardBlock'][0])
    {
        $returnType = '';
        $request = $this->updateDashboardBlockRequest($dashboard_id, $block_id, $update_dashboard_block_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateDashboardBlock'
     *
     * @param  string $dashboard_id Dashboard ID (required)
     * @param  string $block_id Block ID (required)
     * @param  \Omnismith\Model\UpdateDashboardBlockRequest $update_dashboard_block_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateDashboardBlock'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateDashboardBlockRequest($dashboard_id, $block_id, $update_dashboard_block_request, string $contentType = self::contentTypes['updateDashboardBlock'][0])
    {

        // verify the required parameter 'dashboard_id' is set
        if ($dashboard_id === null || (is_array($dashboard_id) && count($dashboard_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $dashboard_id when calling updateDashboardBlock'
            );
        }

        // verify the required parameter 'block_id' is set
        if ($block_id === null || (is_array($block_id) && count($block_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $block_id when calling updateDashboardBlock'
            );
        }

        // verify the required parameter 'update_dashboard_block_request' is set
        if ($update_dashboard_block_request === null || (is_array($update_dashboard_block_request) && count($update_dashboard_block_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_dashboard_block_request when calling updateDashboardBlock'
            );
        }


        $resourcePath = '/dashboards/{dashboardId}/blocks/{blockId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($dashboard_id !== null) {
            $resourcePath = str_replace(
                '{' . 'dashboardId' . '}',
                ObjectSerializer::toPathValue($dashboard_id),
                $resourcePath
            );
        }
        // path params
        if ($block_id !== null) {
            $resourcePath = str_replace(
                '{' . 'blockId' . '}',
                ObjectSerializer::toPathValue($block_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_dashboard_block_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_dashboard_block_request));
            } else {
                $httpBody = $update_dashboard_block_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires Bearer (JWT) authentication (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
